/*
    SDIO definitions

    Copyright (C) 2023 lifehackerhansol

    SPDX-License-Identifier: Zlib
*/

#pragma once

#define SDIO_CMD0_GO_IDLE_STATE 0
#define SDIO_CMD2_ALL_SEND_CID 2
#define SDIO_CMD3_SEND_RELATIVE_ADDR 3
#define SDIO_CMD7_SELECT_CARD 7
#define SDIO_CMD8_SEND_IF_COND 8
#define SDIO_CMD9_SEND_CSD 9
#define SDIO_CMD12_STOP_TRANSMISSION 12
#define SDIO_CMD13_SEND_STATUS 13
#define SDIO_CMD16_SET_BLOCK_LEN 16
#define SDIO_CMD17_READ_SINGLE_BLOCK 17
#define SDIO_CMD18_READ_MULTIPLE_BLOCK 18
#define SDIO_CMD24_WRITE_SINGLE_BLOCK 24
#define SDIO_CMD25_WRITE_MULTIPLE_BLOCK 25
#define SDIO_CMD55_APP_CMD 55
#define SDIO_CMD58_READ_OCR 58

#define SDIO_ACMD6_SET_BUS_WIDTH 6
#define SDIO_ACMD41_SD_SEND_OP_COND 41
