name: Build nightly

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'README.md'
      - archived
      - default
      - staging
      - template
      - tools
  workflow_dispatch:

jobs:
  devkitarm:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - uses: actions/checkout@v4
      - name: Build all drivers
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          path: out
          name: build_dka
  blocksds:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    name: Build with Docker using BlocksDS
    steps:
      - uses: actions/checkout@v4
      - name: Build all drivers
        run: |
          cd blocksds
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          path: blocksds/out
          name: build_blocks

  publish:
    runs-on: ubuntu-latest
    name: Publish artifacts
    needs: [devkitarm, blocksds]
    steps:
      - name: Checkout artifact branch
        uses: actions/checkout@v4
        with:
          path: artifacts
          ref: builds
      - name: Download devkitARM artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_dka
          path: /tmp/build_dka
      - name: Download BlocksDS artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_blocks
          path: /tmp/build_blocks
      - name: Commit artifacts
        continue-on-error: true
        run: |
          rm -rf artifacts/*.dldi
          cp -r /tmp/build_dka/*.dldi artifacts/
          cp -r /tmp/build_blocks/*.dldi artifacts/
          cd artifacts
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Build: ${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          directory: artifacts
          branch: builds
